### PR TITLE
Bump libgit2

### PR DESCRIPTION
**Pull request by joshaber**

### CODE REVIEW

**Comment by phatblat** [comment]
Bumping libgit2 is so exciting lately :fearful:

**Comment by joshaber** [comment]
>Don't forget, you've got a focused test here.

Yup, this is highlighting a legit libgit2 bug.

**Comment by joshaber** [comment]
This is currently blocked by https://github.com/libgit2/libgit2/issues/3284.

**Comment by joshaber** [comment]
This is ready for review now :pray:

**Comment by phatblat** [comment]
Looks good :icecream:

**Pull request merged**
