### PR TITLE
Enable Bitcode

### PR DESCRIPTION
**Pull request by pietbrauer**
It may eventually, under certain circumstance work on my machine. It may also be a pretty naive attempt on solving this issue.

I tried to solve this while adding a tvOS target and at least the compiler did not complain anymore that bit code must be enabled (which it did before). It does not seem that `lipo` is stripping any symbols and OpenSSL can just be compiled using bitcode as describes by these fine gentleman here: https://gist.github.com/felix-schwarz/c61c0f7d9ab60f53ebb0

### CODE REVIEW

**Comment by pietbrauer** [comment]
Somehow `Creating_a_blame_with_options__should_follow_the_instructions_provided_by_the_GTBlameOptionsOldestCommitOID_key_Userstravisbuildlibgit2objectivegitObjectiveGitTestsGTBlameSpecm_61 ` get stuck on iOS 🤔

**Comment by phatblat** [comment]
You can validate whether the output binaries contain bitcode with 'otool -l file | grep bitcode'

**Comment by pietbrauer** [comment]
Did that, they all do 😊

**Comment by phatblat** [comment]
Sweet! Either lipo changed or I was doing something wrong. Most likely the latter.

**Comment by pietbrauer** [comment]
Most likely I miss something important 😀 Have to check again an integrate it into an actual app. When I did with tvOS I got the stupid umbrella header errors again.

**Comment by pietbrauer** [comment]
I will wait for #555 and #554 to be merged before tackling it again, the tests are really unreliable at the moment. See the current master build, which was green in the PullRequest https://travis-ci.org/libgit2/objective-git/builds/111554295

**Comment by pietbrauer** [comment]
@phatblat green :+1:

**Comment by phatblat** [comment]
You did it! I'll look this over.

**Comment by phatblat** [comment]
Just a note - due to the nature of the build scripts not rebuilding things, static libraries built from a commit before this change will cause one or more of the following linker errors due to not being built with bitcode.

```
ld: 'External/ios-openssl/lib/libssl.a(s2_meth.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
ld: 'External/libssh2-ios/lib/libssh2-ios.a(channel.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
ld: 'External/libgit2-ios/libgit2-ios.a(annotated_commit.c.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

No surprise, but in case anyone runs across this in the future, just remove these files and rebuild.

```bash
rm External/ios-openssl/lib/libssl.a
rm External/libssh2-ios/lib/libssh2-ios.a
rm External/libgit2-ios/libgit2-ios.a
```

**Comment by phatblat** [comment]
```
otool -l External/libssh2-ios/lib/libssh2-ios.a | grep bitcode | head -n 1
 sectname __bitcode
otool -l External/ios-openssl/lib/libssl.a | grep bitcode | head -n 1
 sectname __bitcode
otool -l External/ios-openssl/lib/libssl.a | grep bitcode | head -n 1
 sectname __bitcode
otool -l /Volumes/DerivedData/ObjectiveGitFramework-drtqacfhlqybdcdpqayztrrwneun/Build/Products/Debug-iphoneos/ObjectiveGit.framework/ObjectiveGit  | grep __LLVM | head -n 1
  segname __LLVM
```



_Apparently, [__LLVM](https://forums.developer.apple.com/thread/3971#jive-1718624311518484076863) is a better string to search for_

**Pull request merged**
