### PR TITLE
ZipArchive 1.1

### PR DESCRIPTION
**Pull request by phatblat**
Now consuming the framework instead of source in iOS Tests target

### CODE REVIEW

**Comment by pietbrauer** [comment]
Build failed because of the warnings in the project.

**Comment by phatblat** [comment]
Yeah, I saw that earlier with the 1.1 update while the iOS Test target was directly compiling the ZipArchive source.

```
/Users/travis/build/libgit2/objective-git/Carthage/Checkouts/ZipArchive/SSZipArchive/minizip/zip.c:950:6: error: expression result unused [-Werror,-Wunused-value]
    (crcForCrypting);
     ^~~~~~~~~~~~~~
1 error generated.
```

Strange that I don't get this error when building the ZipArchive-iOS framework target locally or when building the iOS Tests :weary:

**Comment by phatblat** [comment]
Ah, the Mac Tests are failing because they are still compiling the ZipArchive source directly.

**Comment by pietbrauer** [comment]
This would've been spotted by #554 😉

**Comment by pietbrauer** [comment]
So much better now. Thanks!

**Pull request merged**
