### PR TITLE
[WIP] Git2 framework

### PR DESCRIPTION
**Pull request by phatblat**
Migrating phatblat/objective-git#1 into the main project. Also collapsed separate https://github.com/phatblat/git2 repo into this one, but kept the git2 Xcode project separate as a subproject. This way, git2 takes care of building the OpenSSL and libssh2 static libraries, which are only used by libgit2 and the output is a `git2.framework` that sits alongside `ObjectiveGit.framework`.

The real reason for this change is to treat `git2` as a real module instead of a submodule (`ObjectiveGit.git2`) finally resolving those pesky module issues since the libgit2 `#import`s are expecting "git2" at the top level.

Addresses #436, #523, #542

I'm sure there's some cleanup necessary before this is ready to merge, but it should be good enough for review in this initial state.

### CODE REVIEW

**Comment by alehed** [comment]
Any chance this can already be used for production work?

**Comment by alehed** [comment]
I tried it out and it seems to work. The problem was that it kept complaining about `inttypes.h` not being modular in common.h. Commenting it out and adding the missing dependency directly to config.c seemed to do the trick. Not quite sure what's best to do on the long run though.

**Comment by phatblat** [comment]
@alehed Yes, this branch with new Xcode build for libgit2 works, I've been playing around with it in a hobby app for months. Fixing those module errors coming from `inttypes.h` was one of the goals of this change, and as you can see it doesn't resolve it. 😞

**Comment by pietbrauer** [comment]
What's the state of this noting that we get the same non modular header error again, even with the framework?

**Comment by phatblat** [comment]
I have mixed feelings about this. I'm disappointed that this change doesn't solve one of the main reasons for it. However, I do think that an Xcode-based build will be easier to maintain than a cmake wrapper script. Also, the build is slightly faster since each architecture can build in parallel.

**Comment by tiennou** [comment]
Can you guys give a spin to https://github.com/libgit2/libgit2/pull/3781, see how it works for you ? 

IIRC I got to the point where I had a linkable `git2.framework`, but wasn't able to package the various dependencies so I don't think it would work as a module import.

**Comment by alehed** [comment]
I'm currently trying to update it for master (see [alehed/git2_framework_v251](https://github.com/alehed/objective-git/tree/git2_framework_v251)), but I'm having trouble with pthread (it's giving me the "implicit declaration" and "undefined symbol" treatment). The `inttypes` problem can probably be taken care of upstream.

@tiennou personally, I think building from source using it's own module is preferable over linking it with a pre-packaged framework (at least for development), but that is just my opinion. Manually updating it for every libgit2 release is a pain but I don't see an alternative.

@phatblat did you encounter anything like that when you created git2.xcodeproj?

**Comment by tiennou** [comment]
The alternative I was proposing was to make the CMake Xcode generator work correctly in libgit2 itself (which would take care of the pain of manual updates), so I don't understand your point about pre-packaged. What I was missing is a way to make CMake copy the (built) dependencies (openssl & friends) at the correct place in the generated libgit2, so the resulting framework would be self-sufficient.

**Comment by alehed** [comment]
What I don't like about cmake generated Xcode projects is that they work using extra scripting hooks that rely on cmake and they also have a weird target system. If there was a way to generate a clean Xcode project that is contained in itself, I would go for that.

It is possible to copy around files using the cmake syntax (using the `configure_file` command, but I don't remember exactly how to do it).

**Comment by tiennou** [comment]
Sorry, my memory is too hazy to remember what you're defining as "weird target system". If you want to investigate, I just rebased my PR against `master`, so you can give it a spin.

From your `libgit2` tree, `mkdir build && cd build && cmake -G Xcode -DBUILD_FRAMEWORK=ON ..`. You'll end up with a libgit2.xcodeproj with a git2 "framework" target. Obviously, this is all WIP 😉 .

**Comment by alehed** [comment]
I should have probably used the wording "excessive targets":

targets

vs.

targets2

The good news is that it builds. Maybe I can use it to fix the manual Xcode project.

**Comment by pietbrauer** [comment]
I am closing this as no one has pushed to this PR in a year. Feel free to reopen if still valid.

**Pull request closed without merging**
