### PR TITLE
Recent brew list sysntax

### PR DESCRIPTION
**Pull request by hannesa2**
*** Updating submodules...
*** Checking dependencies...
Error: Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead.

### CODE REVIEW

**Comment by tiennou** [comment]
Thanks for the PR, @hannesa2 !

**Comment by hannesa2** [comment]
@tiennou whats about #710 ?

**Comment by tiennou** [comment]
I'm not opposed to it, but right now my priority is to (try to) get a release out with updated dependencies, and I depend on CI handling iOS correctly, which #710 doesn't.

But this is so flaky it's not fun. I can usually build fine locally (at least #713 did, and on CI as well). But then #714's macOS build [failed to test](https://travis-ci.org/github/libgit2/objective-git/jobs/770000140) by failing to find headers 😭.

**Comment by hannesa2** [comment]
But you can't know, if #710 works properly, when you don't merge it.
It will start running, when you merge it 

Here https://github.com/hannesa2/objective-git/pull/2 you can see it in advance, how does it work. Please give it a try

**Pull request merged**
