### PR TITLE
Using the latest & greatest libgit2 code

### PR DESCRIPTION
**Pull request by slavikus**

### CODE REVIEW

**Comment by pietbrauer** [comment]
I was waiting for a new release containing my Xcode 7.3 fix. #564 updates to 0.24.0, as far as I understand the release schedule for libgit2 a new version should land in the beginning of next month.

I am quite curious why we always update to HEAD for libgit2 instead of using the releases?

**Comment by slavikus** [comment]
Sticking to releases sounds more reasonable than tailing to HEAD, actually. I was stuck with Obj-Git not compiling after upgrading to 7.3, so it was more of a quick move rather than a strategic decision.

**Comment by pietbrauer** [comment]
@carlosmn do you know when you guys plan to do a new release of `libgit2`?

**Comment by carlosmn** [comment]
We'll aim to have a maintenance release roughly every month and a larger one every six months, but real life interferes sometimes.

**Comment by pietbrauer** [comment]
I have update #564 to use your commit on libgit2. As my branch already includes the fix for the tests I am closing this one.

**Comment by slavikus** [comment]
Fair enough. Thanks!

**Pull request closed without merging**
