### PR TITLE
Add merge analysis between two branches

### PR DESCRIPTION
**Pull request by alehed**
If you want to check the feasibility of a merge between two branches, this might come in handy.

### CODE REVIEW

**Review by pietbrauer — CHANGES_REQUESTED** [review]
Thanks again! Tests would be very nice here as well.

**Comment by alehed** [comment]
To my knowledge there is no way to get ObjectiveGit to give me an  "unborn" branch, that is one with an empty SHA, so GTMergeAnalysisUnborn is never returned.

**Comment by alehed** [comment]
Any idea why the test fails? Locally the (iOS) tests all succeed with the newer versions of Quick and Nimble.

**Comment by pietbrauer** [comment]
My guess is that we are still running tests with Xcode 8.0 on Travis until #631 is merged. There could be some changes in Xcode and/or Nimble and Quick that cause this.

**Comment by alehed** [comment]
Hope the tests pass now.

**Comment by tiennou** [comment]
About "unborn" : you can get one by deleting the ref pointed to by `HEAD`.

Since you can only merge a branch in `HEAD`, I'm wondering about the use case for that method.

**Comment by alehed** [comment]
The reason why I needed this is for pulling a branch other than the current one. Think `git pull origin master` while you are on branch `feature-1`.

**Comment by tiennou** [comment]
@pks-t @ethomson Would you guys be interested in having that capability upstream ? I'm a little wary of adding API not backed by what's in The Library...

**Comment by ethomson** [comment]
Yeah; it seems that this is similar to giving `git_merge_analysis` the knowledge of a different `ours`.  I can see how that would be useful.

**Comment by alehed** [comment]
Now with upstream having this feature, the PR would have to be reworked completely. I'm not working on this any more, so closing.

**Pull request closed without merging**
