### PR TITLE
Enable verbose build output from iOS build scripts

### PR DESCRIPTION
**Pull request by phatblat**
An attempt to work around Travis build timeouts due to lack of output from the build (mentioned in #464).

Let's see if Travis succeeds on this PR 🙏🏽

### CODE REVIEW

**Comment by joshaber** [comment]
It would seem not :cry:

**Comment by pietbrauer** [comment]
My suggestion would be to run `script/update_lib*` manually before we start `xctool` this way it produces output & runs fast with `xctool` (because the libraries already exist). I could take care of it unless @phatblat really really wants to do it. I don't think the verbose mode is needed.

**Comment by phatblat** [comment]
@pietbrauer got for it. There's an issue with this change where Xcode treats some output from configure as an error.

**Comment by phatblat** [comment]
I'm going to close this until I can figure out a good way to deal with that configure output. Don't want to hide it but don't want Xcode to think it's an error.

**Pull request closed without merging**
