### PR TITLE
Update modulemap

### LINKED ISSUE #467: Update modulemap
I'm seeing a lot of warning with Xcode 6.3.2 like:

```
<module-includes>:1:1: Umbrella header for module 'ObjectiveGit' does not include header '/git2/cred_helpers.h'
```

### PR DESCRIPTION
**Pull request by joshaber**
Mostly fixes #467.

We're still getting:

```
Umbrella header for module 'ObjectiveGit' does not include header '/git2/inttypes.h'
Umbrella header for module 'ObjectiveGit' does not include header '/git2/stdint.h'
Umbrella header for module 'ObjectiveGit' does not include header '/git2/sys/git2/inttypes.h'
Umbrella header for module 'ObjectiveGit' does not include header '/git2/sys/git2/stdint.h'
```

But those are Windows-specific so we don't actually want them. I'm not sure how to silence the warning.

### CODE REVIEW

**Comment by mdiep** [comment]
I don't think you're supposed to include any of the `/git2/sys` headers.

**Comment by joshaber** [comment]
Any idea how to silence the warnings about them?

**Comment by joshaber** [comment]
Looks like we should be able to exclude the headers, maybe.

**Comment by mdiep** [comment]
Oh! Xcode is complaining about those because they're being copied into the framework. ObjectiveGit is set up with a folder reference with all the libgit2 headers that's copied into the framework.

The solution is to use a group instead of a reference so you can exclude the headers that we don't want from `ObjectiveGitFramework.xcodeproj` and from the Copy Headers build phase.

**Comment by mdiep** [comment]
(SwiftGit2 does it this way. You should be able to use it as a reference if you need one.)

**Comment by pietbrauer** [comment]
Wouldn't this break integrations for some people that use ObjetiveGit and libgit2 directly?

**Comment by joshaber** [comment]
Interestingly we were already copying the headers. I'm not sure why we had the additional reference.

>Wouldn't this break integrations for some people that use ObjetiveGit and libgit2 directly?

libgit2's headers are still exposed.

This is ready for review again :pray:

**Comment by mdiep** [comment]
> > Wouldn't this break integrations for some people that use ObjetiveGit and libgit2 directly?
>
> libgit2's headers are still exposed.

Some of libgit2's headers are platform-dependent. We're just excluding the ones that don't apply to OS X/iOS.

**Comment by mdiep** [comment]
Xcode is giving me those warnings—even on `master`—but this looks good.

**Pull request merged**
