### PR TITLE
Update libgit2 to 0.26

### PR DESCRIPTION
**Pull request by tiennou**
Now that 0.26 is a thing.

Tests have been run locally.

### CODE REVIEW

**Comment by pietbrauer** [comment]
Seems that Travis can't checkout one of the libgit2 example repositories?

**Comment by tiennou** [comment]
Yep, they have a deliberately broken submodule file that `--recursive` tries to update.

libgit2/libgit2#4274

**Comment by tiennou** [comment]
I've repointed the submodule to my fixed branch (which is `maint/0.26` + the submodule delete) so this should be good as a first approximation.

**Comment by pietbrauer** [comment]
I personally wouldn't like a "personal" fork of libgit2 for the submodule. We should wait for the issue to be fixed on there side.

**Comment by slavikus** [comment]
Looks like libgit2 got this fixed, can we get back to  this one, guys?

**Comment by pietbrauer** [comment]
I’m all for it.

**Comment by tiennou** [comment]
Updated !

**Comment by pietbrauer** [comment]
Sweet!

**Pull request merged**
