### PR TITLE
Prebuild OpenSSL in order to workaround Travis timouts

### PR DESCRIPTION
**Pull request by pietbrauer**

### CODE REVIEW

**Comment by joshaber** [comment]
:sparkles: 

That test failure is https://github.com/libgit2/libgit2/issues/3318.

**Comment by pietbrauer** [comment]
If #496 did help fixing the issue the tests should be green now.

**Comment by phatblat** [comment]
Nice. Looks like that did it. 🍹

**Comment by mdiep** [comment]
Nicely done! :metal:

**Pull request merged**
