### PR TITLE
Update libgit2 to v0.27.4

### PR DESCRIPTION
**Pull request by tiennou**
This updates libgit2 to recently released libgit2 v0.27.4, which is is a security release.

@pietbrauer If that's okay with you, I'll do a 0.14.1 after that, 'cause we're still missing the submodule fixes from 0.27.3…

### CODE REVIEW

**Comment by pietbrauer** [comment]
Fine with me, if CI is green feel free to merge.

**Comment by tiennou** [comment]
Just a question, because I don't remember doing anything specific the last time : the [release](https://github.com/libgit2/objective-git/releases) I just did has no Objective-Git.framework archive, and the build went fine. Am I missing something ? Or is my memory failing me hard 😉  ?

**Comment by pietbrauer** [comment]
All you have to do is `Carthage build —no-skip-current` and then `carthage Archive ObjectiveGit` does this work for you?

**Comment by tiennou** [comment]
Worked like a charm, thanks ! I'll attach that to the release then.

**Pull request merged**
