### PR TITLE
Wrap git_index_add_all

### PR DESCRIPTION
**Pull request by alehed**
Allows the user to do something like `git add -A`

### CODE REVIEW

**Comment by alehed** [comment]
Sure, I just thought the test suite is ignored on this project.

**Comment by pietbrauer** [comment]
I look at it. We "just" have one failing test on macOS which is consistent 😆. iOS is a different story.

**Comment by alehed** [comment]
Yeah, would be great if all the tests worked... But I do too see the value in testing.

I'll probably get around to the tests this weekend.

**Comment by pietbrauer** [comment]
Yeah, many people have spent many hours trying to fix the tests. Thanks a lot! No pressure from my side 😅

**Comment by alehed** [comment]
#599 has a green iOS build, but it is already 5 months old.

**Comment by pietbrauer** [comment]
Let's see what https://travis-ci.org/libgit2/objective-git/builds/237270148 brings.

**Comment by pietbrauer** [comment]
Turns out it wasn't that hard. #631 has a green build. Thanks for pushing this @alehed!

**Comment by alehed** [comment]
@pietbrauer Thanks for fixing the build! 👍

**Comment by alehed** [comment]
I added a small test.

**Pull request merged**
