### PR TITLE
Add stash apply & pop support

### PR DESCRIPTION
**Pull request by tiennou**
Sorry, there's no test in there because I wasn't running the greatest and latest Xcode when I wrote that, and time is pretty scarce yadda yadda.

### CODE REVIEW

**Comment by joshaber** [comment]
Those build failures look legit. Looks like the PR was written against a different version of libgit2.

**Comment by tiennou** [comment]
Oh my fault, I failed to build the correct target before pushing, and the stash API now has a "nice" `git_stash_options` struct. I'll update the API and try to write some of those tests then...

**Comment by joshaber** [comment]
Sorry, I totally missed that this was ready for re-review.

It looks good to me. :+1: Just wanna confirm that this is done from your point of view too.

**Comment by tiennou** [comment]
My only grudge against it is that it's untested (like, I didn't actually use it, just wrote the wrappers). I *might* add test cases soon-ish, but if you want to merge, please do.

**Comment by joshaber** [comment]
Oh lol I totally didn't notice that. Tests would be good :+1:

**Comment by tiennou** [comment]
Here are some tests. I also made a little tweak to the signatures because I noticed those pesky error pointers weren't at the "right" place...

Note that this is not designed to handle conflicts at the moment, since `git_stash_options` embeds a `git_checkout_options` structure, this would make a messy parameter list. Related to #459. So the path forward here is either that other PR, or providing
```
- applyStashAtIndex:flags:checkoutStrategy:checkoutNotify:error:stashProgressBlock:checkoutProgressBlock:checkoutNotifyBlock:
```

:worried:

**Comment by joshaber** [comment]
Ugh yeah, I think that PR is our best way forward on that front.

This looks good :metal:

**Pull request merged**
