### PR TITLE
Add list of files to merge conflict error

### PR DESCRIPTION
**Pull request by pietbrauer**
Currently we only return `Merge conflict, pull aborted` when a merge conflict is detected while pulling this enumerates the conflicted files and returns `Merge conflict in files: index.html, _includes/head.html. Pull aborted.`.

Enumeration should be ok as it is most likely run in a background thread anyway. What do you think?

### CODE REVIEW

**Comment by tiennou** [comment]
Maybe store that in the error's user info ?

**Comment by pietbrauer** [comment]
Yeah true, will fix that.

**Comment by joshaber** [comment]
I'm inclined to say that we should leave doing this in the users' hand. They may very well want a different error message, want it localized, etc.

**Comment by tiennou** [comment]
Depends. It seems the index where conflicts originated is not accessible externally, so you'll have to perform the pull by hand afterward to get the conflicted list.

**Comment by pietbrauer** [comment]
Yep, exactly My intention. To get the list of files we have to rebuild the pull feature.

**Comment by joshaber** [comment]
Eh, yeah, fair enough.

**Comment by pietbrauer** [comment]
@joshaber I will do another PR that sets the conflicted files in the user info?

**Comment by joshaber** [comment]
Yep that's be great!

**Pull request merged**
